---
collect_market_data_task1:
  description: 'Based on {type}, Search the {market_data_url} for relevant market research data, focusing
    on the specific area of interest: {research_focus}. Gather the most insightful
    data points that can inform the analysis.'
  expected_output: A collection of concise insightful market research data relevant to {research_focus}
    sourced from {market_data_url}. Update the output with separate section containing {type}
  async_execution: false
  agent: DataCollector1


analyze_insights_task1:
  description: 'Based on {type},Analyze the collected market data based on the research focus: {research_focus}.
    Derive actionable insights that can guide strategic decision-making.'
  expected_output: A 2 line report detailing actionable insights derived from the market
    data analysis relevant to {research_focus}. Update the output with separate section containing {type}
  async_execution: false
  agent: DataAnalyser1
  context:
  - collect_market_data_task1


data_output_task1:
  description: 'Based on,Collate the data from insights.'
  expected_output: A 2 line summary report of actionable insights derived from analyze insights task.
  async_execution: false
  agent: DataOutput1
  context:
  - analyze_insights_task1